version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: update.
          command: apt-get update
      - run:
          name: Install git.
          command: apt-get install -y git
      - run:
          name: Install make,cmake.
          command: apt-get install -y make cmake
      - run:
          name: Install clang
          command: apt-get install -y clang
      - run:
          name: Install libhunspell
          command: apt-get install -y libhunspell-1.3.0 libhunspell-dev
      - run:
          name: Install libxerces
          command: apt-get install -y libxerces-c3-dev
      - run:
          name: Install boost
          command: apt-get install -y libboost1.58-dev libboost-system1.58.0 libboost-program-options1.58-dev libboost-filesystem1.58-dev libboost-date-time1.58-dev libboost-regex1.58-dev
      - run:
          name: change c++.
          command: update-alternatives --set c++ /usr/bin/clang++
      - run:
          name: change cc.
          command: update-alternatives --set cc /usr/bin/clang
      - run:
          name: submodule init.
          command: git submodule init
      - run:
          name: submodule update.
          command: git submodule update
      - run:
          name: change dir.
          command: cd library/SimpleXmlWriter/
      - run:
          name: mkdir .ssh
          command: mkdir -p ~/.ssh && chmod 700 ~/.ssh
      - run:
          name: add ssh_config
          command: echo "host *" >> ~/.ssh/config
      - run:
          name: add ssh_config
          command: echo "      StrictHostKeyChecking no" >> ~/.ssh/config
      - run:
          name: update.
          command: git pull origin dev
      - run:
          name: change dir.
          command: cd ../../
      - run:
          name: run cmake
          command: cmake .
      - run:
          name: run make.
          command: make
