version: 2.0
jobs:
  build:
    docker:
      - image: gesuno/ubuntu:v0.0.1
    steps:
      - checkout
      - run:
          name: submodule init.
          command: git submodule init
      - run:
          name: submodule update.
          command: git submodule update
      - run:
          name: mkdir .ssh
          command: mkdir -p ~/.ssh && chmod 700 ~/.ssh
      - run:
          name: add ssh_config
          command: echo "host *" >> ~/.ssh/config
      - run:
          name: add ssh_config
          command: echo "      StrictHostKeyChecking no" >> ~/.ssh/config
      - run:
          name: run cmake
          command: cmake .
      - run:
          name: run make.
          command: make
  test:
    docker:
      - image: docker
    steps:
      - checkout
      - run:
        name: get docker imange
        command: docker pull codeclimate/codeclimate
      - run:
        name: get docker imange
        command: docker pull gesuno/codeclimate-cppcheck
      - run:
        name: Get cc-test-reporter
        command: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run:
        name: chmod +x ./cc-test-reporter
        command: chmod +x ./cc-test-reporter
      - run:
        name: Start reporter
        command: ./cc-test-reporter befor-build
      - run:
        name: Run code climate analyze
        command: /usr/src/app/bin/codeclimate analyze --dev -f json > codeclimate.json
      - run:
        name: Upload report
        command: ./cc-test-reporter after-build
workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test
