version: 2.0
jobs:
  build:
    docker:
      - image: gesuno/ubuntu:v0.0.1
    steps:
      - checkout
      - run:
          name: submodule init.
          command: git submodule init
      - run:
          name: submodule update.
          command: git submodule update
      - run:
          name: mkdir .ssh
          command: mkdir -p ~/.ssh && chmod 700 ~/.ssh
      - run:
          name: add ssh_config
          command: echo "host *" >> ~/.ssh/config
      - run:
          name: add ssh_config
          command: echo "      StrictHostKeyChecking no" >> ~/.ssh/config
      - run:
          name: run cmake
          command: cmake .
      - run:
          name: run make.
          command: make
  test:
    docker:
      - image: codeclimate/codeclimate
    steps:
      - checkout
      - run:
          name: Run code climate analyze
          command: codeclimate analyze
workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test
